name: Build and Release ChainReact

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v1.1.1, etc.

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 🧾 Checkout code
      uses: actions/checkout@v3

    - name: 🛠 Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Replace if you're using .NET 6 or 7

    - name: 📦 Restore dependencies
      run: dotnet restore

    - name: 🚀 Publish CR (Portable Build)
      run: dotnet publish -c Release -r win-x64 --self-contained false -o output

    - name: 🗜 Compress build
      run: Compress-Archive -Path output\* -DestinationPath ChainReact.zip

    - name: 📤 Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: ChainReact.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
